version: '3'
services:
  web:
    image: discord_clone_web:0.0.1
    build: .
    command: bash -c "node api/index.js"
    restart: always
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"
